[package]
name = "syncing_circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_prototype_lyon = "0.5.0"
bevy_egui = "0.14.0"
bevy_mod_debugdump = "0.4.0"